version: "3.7"
services:
  app:
    build:
      args:
        user: apiuser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: api-image
    container_name: api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network-api
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: hUt4kPse
      MYSQL_PASSWORD: hUt4kPse
      MYSQL_USER: apiuser
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - network-api
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network-api
networks:
  network-api:
    driver: bridge